# Generated by Django 5.2 on 2025-06-30 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_connect', '0004_volunteeropportunity_volunteersignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='opportunities/'),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='max_volunteers',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='volunteersignup',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteersignup_set', to='recycle_connect.volunteeropportunity'),
        ),
    ]
