# Generated by Django 5.2 on 2025-07-10 05:25

import recycle_connect.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle_connect', '0012_remove_poll_post_poll_created_at_postreaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recycle_connect.models.material_image_upload_path),
        ),
    ]
